#!/bin/sh

if [ "$#" -ne 1 ]
then
  echo "Usage: `basename "$0"` rolename"
  exit 1
fi

#NOTE: this script was intended to be run from the same folder as the newrole folder.  If you would like to do otherwise, change the DIR value below

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
# get the directory of this script
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

echo "creating new role $1 at $(pwd)/$1"
ansible-playbook "$DIR/run.yml" -i $DIR/inv-localhost -c local -e "newrole_dest=$(pwd) newrole_name=$1"
